default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Angler_development

test:
  <<: *default
  database: Angler_test

production:
  <<: *default
  database: Angler_production
  username: root
  password: <%= ENV['ANGLER_DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
