# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9becb42ffe372b35d66b16524069bb45a0f2dfa0e5de6c6b95eb1f1e92391ea565b0c2e2e095d7c7ac7015c126c515c737f4d6eb42879c50bcc778d8eba4eee1

test:
  secret_key_base: 67f672da71e51875786e125316936e6789ad11489fde60ae8397b253c68990a7db52dcaf47f3fe16041c9e1a93ed0e087cd4174f86712dbe35bd3d23a4df0cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
